<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProductColor;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $colors = [
            ['name' => 'Ashen Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fossil Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Steel Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gunmetal Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Smoky Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Stone Gray', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Harbor Gray', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Emerald Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lime Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Olive Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Army Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Forest Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mint Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Spearmint Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seafoam Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jade Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peacock Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lime Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pear Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chartreuse', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pale Celadon', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Laurel Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kelly Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hunter Green', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Tangerine Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Apricot Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peach Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burnt Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Clay Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiger Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Honey Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rust Orange', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ochre Orange', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Crimson Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Scarlet Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ruby Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cherry Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burgundy Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chestnut Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wine Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brick Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Salmon Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Terra Cotta', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rusty Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fire Engine Red', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maroon', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Redwood', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Raspberry Red', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Gold Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Goldenrod Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mustard Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Canary Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maize Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mellow Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bumblebee Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trombone Yellow', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuscany Yellow', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Midnight Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Royal Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Navy Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cobalt Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Azure Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sky Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sapphire Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Deep Sapphire', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pale Ice Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ice Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Icy Mint', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiffany Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Steel Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lavender Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cornflower Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yale Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Egyptian Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkish Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Carolina Blue', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Denim Blue', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Chocolate Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chestnut Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Auburn Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cedar Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peanut Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bread Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Caramel Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tawny Brown', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umber Brown', 'created_at' => now(), 'updated_at' => now()],




            ['name' => 'Lavender', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Periwinkle', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thistle', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plum', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dark Plum', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Reddish Plum', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Violet', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauve', 'created_at' => now(), 'updated_at' => now()],


            ['name' => 'Ruby Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rose Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hot Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ultra Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Amaranth Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'French Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Creamy Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Punch Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Light Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pastel Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brick Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bubblegum Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Salmon Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Coral Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Magenta Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cerise', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fuchsia', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thulian Pink', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lemonade', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flamingo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Carnation', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Taffy', 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Charcoal', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slate', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ash', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Steel', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ivory White', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pearl White', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cream White', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aqua', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turquoise', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Teal', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Celeste', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Amethyst', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Orchid', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lilac', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aquamarine Turquoise', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyan Turquoise', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dark Teal', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Blue-Green', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Beige', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khaki', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Coral', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peach', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Coral', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brass Gold', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rose Gold', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Copper Gold', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pink Gold', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Metallic Silver', 'created_at' => now(), 'updated_at' => now()],


            ['name' => 'Aubergine', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eggplant Purple', 'created_at' => now(), 'updated_at' => now()],
            
            ['name' => 'Taupe', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mushroom', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Greige', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lilac', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pale Lilac', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Deep Lilac', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burnt Sienna', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Terra Cotta', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saffron', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Topaz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Amber', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Honey Topaz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Amber', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mulberry', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hibiscus', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eggplant', 'created_at' => now(), 'updated_at' => now()],
        ];

        ProductColor::insert($colors);
    }
}
